********************************************************************************
*                                                                              *
* Filename: hh2gen_labelling.do                                                *
* Description: a little snippet to re-label the created variables in the       *
*   previous datasets in a friendly way, so that can also be consulted by a    *
*   person who has no idea of what is going on, e.g. me.                       *
*                                                                              *
********************************************************************************

label language EN

label variable syear         "Survey Year"
label variable fhid          "HH Father Household ID"
label variable mhid          "HH Mother Household ID"
label variable fhid_s        "HP Father Household ID"
label variable mhid_s        "HP Mother Household ID"
label variable fnr           "HH Father Person ID"
label variable mnr           "HH Mother Person ID"
label variable fnr_s         "HP Father Person ID"
label variable mnr_s         "HP Mother Person ID"

label variable fage          "HH Father's Age"
label variable fage_s        "HP Father's Age"
label variable mage          "HH Mother's Age"
label variable mage_s        "HP Mother's Age"
label variable female        "HH Female"
label variable female_s      "HP Female"
label variable ineduc        "HH is still in Education"
label variable ineduc_s      "HP is still in Education"
label variable civserv       "HH is Civil Servant"
label variable civserv_s     "HP is Civil Servant"
label variable selfemp       "HH is Self-Employed"
label variable selfemp_s     "HP is Self-Employed"
label variable employed      "HH is Employed"
label variable employed_s    "HP is Employed"
label variable retired       "HH is Retired"
label variable retired_s     "HP is Retired"

label variable freligion     "HH Father's Religious Group"
label variable freligion_s   "HP Father's Religious Group"
label variable mreligion     "HH Mother's Religious Group"
label variable mreligion_s   "HP Mother's Religious Group"

label variable college       "HH has College Degree"
label variable college_s     "HP has College Degree"
label variable fcollege      "HH Father has College Degree"
label variable fcollege_s    "HP Father has College Degree"
label variable mcollege      "HH Mother has College Degree"
label variable mcollege_s    "HP Mother has College Degree"
label variable hsdegree      "HH has High School Degree"
label variable hsdegree_s    "HP has High School Degree"
label variable fhsdegree     "HH Father has High School Degree"
label variable fhsdegree_s   "HP Father has High School Degree"
label variable mhsdegree     "HH Mother has High School Degree"
label variable mhsdegree_s   "HP Mother has High School Degree"
label variable yeduc         "HH Education in Years"
label variable yeduc_s       "HP Education in Years"
label variable voceduc       "HH has Vocational Education Degree"
label variable voceduc_s     "HP has Vocational Education Degree"
label variable finjob        "HH has a Finance-Related Job"
label variable finjob_s      "HP has a Finance-Related Job"
label variable etecon        "HH has Economic Education or Training"
label variable etecon_s      "HP has Economic Education or Training"
label variable married       "HH is Married"
label variable foreignid     "HH Foreign Identity Scale (1-5)"
label variable foreignid_s   "HP Foreign Identity Scale (1-5)"
label variable langspoken    "HH Usual Lanugage Spoken, 3 levels"
label variable langspoken_s  "HP Usual Lanugage Spoken, 3 levels"
label variable nsibs         "HH Number of Siblings in Original Household"
label variable nsibs_s       "HP Number of Siblings in Original Household"
label variable egp           "HH Last Reached EGP Value (1-11)"
label variable egp_s         "HP Last Reached EGP Value (1-11)"
label variable fegp          "HH Father Last Reached EGP Value (1-11)"
label variable fegp_s        "HP Father Last Reached EGP Value (1-11)"
label variable megp          "HH Mother Last Reached EGP Value (1-11)"
label variable megp_s        "HP Mother Last Reached EGP Value (1-11)"
label variable fhnetinc      "HH Father Monthly Household Net Income, euro"
label variable mhnetinc      "HH Mother Monthly Household Net Income, euro"
label variable fhnetwth      "HH Father Household Overall Net Wealth, euro"
label variable mhnetwth      "HH Mother Household Overall Net Wealth, euro"
label variable fhnetincavg   "HH Father Avg. Monthly Household Net Income, euro"
label variable mhnetincavg   "HH Mother Avg. Monthly Household Net Income, euro"
label variable fhnetwthavg   "HH Father Avg. Household Overall Net Wealth, euro"
label variable mhnetwthavg   "HH Mother Avg. Household Overall Net Wealth, euro"
label variable fhnetinc_s    "HP Father Monthly Household Net Income, euro"
label variable mhnetinc_s    "HP Mother Monthly Household Net Income, euro"
label variable fhnetwth_s    "HP Father Household Overall Net Wealth, euro"
label variable mhnetwth_s    "HP Mother Household Overall Net Wealth, euro"
label variable fhnetincavg_s "HP Father Avg. Monthly Household Net Income, euro"
label variable mhnetincavg_s "HP Mother Avg. Monthly Household Net Income, euro"
label variable fhnetwthavg_s "HP Father Avg. Household Overall Net Wealth, euro"
label variable mhnetwthavg_s "HP Mother Avg. Household Overall Net Wealth, euro"
label variable psamehh       "HH Parents are in the Same Household"
label variable psamehh_s     "HP Parents are in the Same Household"
label variable falive        "HH Father is Alive"
label variable malive        "HH Mother is Alive"
label variable falive_s      "HP Father is Alive"
label variable malive_s      "HP Mother is Alive"
label variable fhsize        "HH Father Current Household Size"
label variable fhsize_s      "HP Father Current Household Size"
label variable mhsize        "HH Mother Current Household Size"
label variable mhsize_s      "HP Mother Current Household Size"
label variable fnative       "HH Father is German"
label variable mnative       "HH Mother is German"
label variable fsecgen       "HH Father is Second-Generation Immigrant"
label variable msecgen       "HH Mother is Second Generation Immigrant"
label variable fnative_s     "HP Father is German"
label variable mnative_s     "HP Mother is German"
label variable fsecgen_s     "HP Father is Second-Generation Immigrant"
label variable msecgen_s     "HP Mother is Second Generation Immigrant"
label variable fstay         "HH Immigrant Father Length of Stay, years"
label variable fstay_s       "HP Immigrant Father Length of Stay, years"
label variable mstay         "HH Immigrant Mother Length of Stay, years"
label variable mstay_s       "HP Immigrant Mother Length of Stay, years"

label variable nchild        "Number of Children (<18) in the Household"
label variable hsize         "Household Size"
label variable owner         "HH owns the Main Residence"
label variable tenant        "HH is a Tenant"
label variable hasloan_pr    "HH has Outstanding Loan/Mortgage Prim. Resid."
label variable hasloan_ot    "HH has Outstanding Loan/Mortgage Other"
label variable hasloans      "HH has Outstanding Loan/Mortgage"
label variable mloan_pr      "HH Monthly Repayment for Loan Prim. Resid, euros"
label variable mloan_ot      "HH Monthly Repayment for Loan Others, euros"
label variable mloans        "HH Monthly Repayment for any Loan, euros"

label variable hhrf          "Household Weighting Factor"
label variable phrf          "HH Weighting Factor"
label variable phrf_s        "HP Weighting Factor"

label copy religion_EN mreligion_EN
label copy religion_EN freligion_EN
label copy religion_EN mreligion_s_EN
label copy religion_EN freligion_s_EN
label values mreligion mreligion_EN
label values freligion freligion_EN
label values freligion_s freligion_s_EN
label values mreligion_s mreligion_s_EN